name = "WNNMDenoise"
uuid = "bf697cf8-868b-4e4c-8c7d-101d0600a0bc"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.0"

[deps]
BlockMatching = "100fd195-2f51-49a3-864c-eaaf5f23bc5e"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageDistances = "51556ac3-7006-55f5-8cb3-34580c88182d"
ImageQualityIndexes = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ImageCore = "0.9"
ImageDistances = "0.2.3"
ImageQualityIndexes = "0.2"
ProgressMeter = "1"
julia = "1.7"
